### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by dmitryzuev** [vdimitroff/ra-compact-ui#3]
Hey, awesome layout for react-admin!

Recently I found an issue with multiple fields in single `RaBox` component.

Example:
```jsx
<RaBox flexGrow={4} display='flex' flexDirection='column'>
  <TextField source='title' />
  <TextField source='subtitle' />
</RaBox>
```

The code above produces following error in console:
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Styled(MuiBox)`. It was passed a child from CompactShowLayout. See https://reactjs.org/link/warning-keys for more information.
```

But if it is a single field in each `RaBox`, no warnings.

Example:
```jsx
<RaBox flexGrow={4} display='flex' flexDirection='column'>
  <RaBox>
    <TextField source='title' />
  </RaBox>
  <RaBox>
    <TextField source='subtitle' />
  </RaBox>
</RaBox>
```

It would be amazing if this minor issue can be fixed.

Thanks!

**Comment by gursimran0410** [comment]
`<RaBox flexGrow={4} display='flex' flexDirection='column'>`
  `['title','subtitle'].map((item,index) => <TextField key={index} source={item} />)`
`</RaBox>`

Why don't you try this instead of writing every multiple fields manually? It will fix the key error as well and will make the code a little more scalable as well.

**Comment by vdimitroff** [comment]
@dmitryzuev Thanks man! I've spotted the issue and actually tried to fix it but didn't have much time then. Will look again and try to resolve the issue.

@gursimran0410 How does this approach make the code more scalable ? And this is rather a workaround, not a fix. Also this approach destroys the native react-admin experience which is a key goal for the library.

**Comment by gursimran0410** [comment]
Talking about the scalability, if you want to specify a new source then you just need to add that source in the array rather than writing a whole new line and I don't feel that this is a workaround as in case of specifying lists than react always needs a key to know which item in a list needs to be updated and using map we can do it easily.

**Comment by shessafridi** [comment]
> @dmitryzuev Thanks man! I've spotted the issue and actually tried to fix it but didn't have much time then. Will look again and try to resolve the issue.

Man your library is epic just need to fix this issue asap

**Comment by shessafridi** [comment]
Thanks for fixing the bug please publish the latest version to NPM.
